#include <Arduino.h>

#define RELE 8 

void setup() {
 
    pinMode(RELE, OUTPUT);
    digitalWrite(RELE, LOW);
}

void loop()
{
    // Liga o relé e a fita LED
    digitalWrite(RELE, HIGH);
    delay(5000);

    // Desliga o relé e a fita LED
    digitalWrite(RELE, LOW);
    delay(5000);
}